use std::path::Path;

pub const TASK_BEGIN: &str = "# >>> cc-loadout tasks (managed) >>>";
pub const TASK_END: &str = "# <<< cc-loadout tasks (managed) <<<";

/// Replace the managed block delimited by (`begin`, `end`) in `existing` with
/// `block`. Empty `block` removes the region. Text outside the markers is verbatim.
pub fn splice(existing: &str, block: &str, begin: &str, end: &str) -> String {
    let lines: Vec<&str> = existing.lines().collect();
    let b = lines.iter().position(|l| *l == begin);
    let e = lines.iter().position(|l| *l == end);

    let mut kept: Vec<&str> = Vec::new();
    match (b, e) {
        (Some(b), Some(e)) if b <= e => {
            kept.extend_from_slice(&lines[..b]);
            kept.extend_from_slice(&lines[e + 1..]);
        }
        _ => kept.extend_from_slice(&lines),
    }
    // Drop any residual orphaned managed markers (exact marker lines only — never
    // touches surrounding user content). Guards against a half-written prior block.
    kept.retain(|l| *l != begin && *l != end);
    while kept.last() == Some(&"") {
        kept.pop();
    }

    let mut out = kept.join("\n");
    if block.is_empty() {
        if !out.is_empty() {
            out.push('\n');
        }
        return out;
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str(block);
    out.push('\n');
    out
}

/// The managed region of `text`: the lines strictly between `TASK_BEGIN` and
/// `TASK_END`, joined by `\n` (empty string when the markers are absent). Used to
/// verify a write actually landed and to detect drift between the live crontab and
/// the schedule rendered from `tasks.json` — both care only about the managed lines,
/// never the surrounding (foreign / crontab-header) content.
pub fn managed_region(text: &str) -> String {
    let lines: Vec<&str> = text.lines().collect();
    let b = lines.iter().position(|l| *l == TASK_BEGIN);
    let e = lines.iter().position(|l| *l == TASK_END);
    match (b, e) {
        (Some(b), Some(e)) if b < e => lines[b + 1..e].join("\n"),
        _ => String::new(),
    }
}

/// Render the managed task block: one `task run <id> --quiet` line per (time, id),
/// ordered by (hour, minute, id) for deterministic, idempotent output.
pub fn render_tasks_block(
    tasks: &crate::task::config::Tasks,
    bin: &Path,
    cron_path: &str,
    home: &Path,
    log: &Path,
) -> String {
    let mut rows: Vec<(u32, u32, &str)> = Vec::new();
    for (id, def) in &tasks.tasks {
        for t in &def.times {
            if let Some((h, m)) = t.split_once(':') {
                if let (Ok(h), Ok(m)) = (h.parse::<u32>(), m.parse::<u32>()) {
                    rows.push((h, m, id.as_str()));
                }
            }
        }
    }
    rows.sort();

    let mut out = String::new();
    out.push_str(TASK_BEGIN);
    out.push('\n');
    out.push_str("# Generated by `cc-loadout task` — edits here are overwritten.\n");
    for (h, m, id) in rows {
        out.push_str(&format!(
            "{m} {h} * * * PATH=\"{cron_path}\" HOME=\"{home}\" \"{bin}\" task run {id} --quiet >> \"{log}\" 2>&1\n",
            home = home.display(),
            bin = bin.display(),
            log = log.display(),
        ));
    }
    out.push_str(TASK_END);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_inserts_when_absent_and_preserves_surroundings() {
        let existing = "# my job\n0 0 * * * backup.sh\n";
        let out = splice(existing, "BLOCK", TASK_BEGIN, TASK_END);
        assert!(out.starts_with("# my job\n0 0 * * * backup.sh\n"));
        assert!(out.contains("BLOCK"));
    }

    #[test]
    fn splice_replaces_existing_block_idempotently() {
        let first = splice(
            "0 0 * * * x\n",
            &format!("{TASK_BEGIN}\nA\n{TASK_END}"),
            TASK_BEGIN,
            TASK_END,
        );
        let second = splice(
            &first,
            &format!("{TASK_BEGIN}\nB\n{TASK_END}"),
            TASK_BEGIN,
            TASK_END,
        );
        assert!(second.contains("B"));
        assert!(!second.contains("\nA\n"));
        let third = splice(
            &second,
            &format!("{TASK_BEGIN}\nB\n{TASK_END}"),
            TASK_BEGIN,
            TASK_END,
        );
        assert_eq!(second, third);
        assert!(second.contains("0 0 * * * x"));
    }

    #[test]
    fn splice_empty_block_removes_managed_region() {
        let with = splice(
            "keep\n",
            &format!("{TASK_BEGIN}\nA\n{TASK_END}"),
            TASK_BEGIN,
            TASK_END,
        );
        let without = splice(&with, "", TASK_BEGIN, TASK_END);
        assert!(!without.contains(TASK_BEGIN));
        assert!(!without.contains("\nA\n"));
        assert!(without.contains("keep"));
    }

    #[test]
    fn splice_strips_orphaned_marker_with_no_end() {
        // Orphaned TASK_BEGIN (no TASK_END) must not accumulate: the stray marker
        // line is removed and the new block applied cleanly. Non-marker content is
        // NOT deleted (we can't prove it was ours).
        let orphaned = format!("keep\n{TASK_BEGIN}\nstale line\n");
        let out = splice(
            &orphaned,
            &format!("{TASK_BEGIN}\nNEW\n{TASK_END}"),
            TASK_BEGIN,
            TASK_END,
        );
        assert_eq!(
            out.matches(TASK_BEGIN).count(),
            1,
            "exactly one TASK_BEGIN (the new block)"
        );
        assert_eq!(
            out.matches(TASK_END).count(),
            1,
            "exactly one TASK_END (the new block)"
        );
        assert!(out.contains("keep"));
        assert!(out.contains("NEW"));
    }

    #[test]
    fn render_tasks_block_one_line_per_time_chronological() {
        use crate::task::config::{Kind, TaskDef, Tasks};
        let mut t = Tasks::default();
        t.tasks.insert(
            "weekly".into(),
            TaskDef {
                kind: Kind::Task,
                account: "work".into(),
                times: vec!["16:00".into(), "07:00".into()],
                prompt: Some("/cortex:weekly".into()),
                cwd: Some(std::path::PathBuf::from("/c")),
                profile: None,
                last_session_id: None,
                last_config_dir: None,
                last_run: None,
                last_status: None,
            },
        );
        let block = render_tasks_block(
            &t,
            std::path::Path::new("/b/cc-loadout"),
            "/b:/usr/bin",
            std::path::Path::new("/home/u"),
            std::path::Path::new("/home/u/task.log"),
        );
        let lines: Vec<&str> = block.lines().collect();
        assert_eq!(lines[0], TASK_BEGIN);
        assert_eq!(*lines.last().unwrap(), TASK_END);
        let cmd: Vec<&str> = lines
            .iter()
            .filter(|l| l.starts_with(|c: char| c.is_ascii_digit()))
            .copied()
            .collect();
        assert!(cmd[0].starts_with("0 7 * * *")); // 07:00 sorts before 16:00
        assert!(cmd[0].contains(r#""/b/cc-loadout" task run weekly --quiet"#));
        assert!(cmd[1].starts_with("0 16 * * *"));
    }

    #[test]
    fn splice_uses_supplied_markers() {
        let out = splice("keep\n", "BLK", TASK_BEGIN, TASK_END);
        assert!(out.contains("keep"));
        assert!(out.contains("BLK"));
    }

    #[test]
    fn managed_region_extracts_inner_lines_and_is_empty_when_absent() {
        let text = format!("keep\n{TASK_BEGIN}\nA\nB\n{TASK_END}\ntail");
        assert_eq!(managed_region(&text), "A\nB");
        assert_eq!(managed_region("no markers here\n0 0 * * * job"), "");
        // Empty managed block (markers adjacent) yields an empty region.
        let empty = format!("{TASK_BEGIN}\n{TASK_END}");
        assert_eq!(managed_region(&empty), "");
    }

    #[test]
    fn managed_region_round_trips_through_splice() {
        // The region read back after a splice equals the inner of the written block.
        let block = format!("{TASK_BEGIN}\n0 8 * * * job\n{TASK_END}");
        let spliced = splice("0 0 * * * foreign\n", &block, TASK_BEGIN, TASK_END);
        assert_eq!(managed_region(&spliced), managed_region(&block));
        assert_eq!(managed_region(&spliced), "0 8 * * * job");
    }
}
